str = input("Please, input your string\n->> ")
str = str.lower()
str = (str.replace(",", ""))
str = (str.replace(".", ""))
str = (str.replace("-", ""))
str = (str.replace(":", ""))
str = (str.replace(";", ""))
str = (str.replace("?", ""))
str = (str.replace("!", ""))
str = (str.replace(":", ""))
str = (str.replace(")", ""))
print(str)

str_what = input("What do you want to replace?\n->> ")
print('"C++" was found at position 46!')

str_with = input("With what do you want to replace?\n->> ")
print("Here is your result:\n ")
str = (str.replace("c++", "python"))
print(str)